services:
  backend-app:
    image: oxygen:latest
    env_file:
      - .env
    environment:
      - MYSQL_HOST=db
      - MYSQL_PASSWORD=password
    ports:
      - '3000:3000'
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: oxygen
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test:
        [
          'CMD',
          'mysqladmin',
          'ping',
          '-h',
          '127.0.0.1',
          '-u',
          'root',
          '-ppassword',
        ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:
